# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import prediction_playground.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediction_playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfusionMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.PositiveIntegerField()),
                ('fp', models.PositiveIntegerField()),
                ('tn', models.PositiveIntegerField()),
                ('fn', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FAMetrics',
            fields=[
                ('basemlmetrics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prediction_playground.BaseMLMetrics')),
                ('accuracy_score', models.DecimalField(decimal_places=7, max_digits=7)),
                ('average_precision_score', models.DecimalField(decimal_places=7, max_digits=7)),
                ('matthews_corrcoef', models.DecimalField(decimal_places=7, max_digits=7)),
                ('cohen_kappa_score', models.DecimalField(decimal_places=7, max_digits=7)),
                ('roc_auc_score', models.DecimalField(decimal_places=7, max_digits=7)),
                ('f1_score', models.DecimalField(decimal_places=7, max_digits=7)),
                ('confusion_matrix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forever_alone.ConfusionMatrix')),
            ],
            options={
                'abstract': False,
            },
            bases=('prediction_playground.basemlmetrics',),
        ),
        migrations.CreateModel(
            name='ForeverAloneEntry',
            fields=[
                ('basedataentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prediction_playground.BaseDataEntry')),
                ('time', prediction_playground.models.BetterDateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('sexuallity', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('income', models.TextField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('bodyweight', models.TextField(blank=True, null=True)),
                ('virgin', models.TextField(blank=True, null=True)),
                ('prostitution_legal', models.TextField(blank=True, null=True)),
                ('pay_for_sex', models.TextField(blank=True, null=True)),
                ('friends', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('social_fear', models.TextField(blank=True, null=True)),
                ('depressed', models.TextField(blank=True, null=True)),
                ('what_help_from_others', models.TextField(blank=True, null=True)),
                ('attempt_suicide', models.TextField(blank=True, null=True)),
                ('employment', models.TextField(blank=True, null=True)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('edu_level', models.TextField(blank=True, null=True)),
                ('improve_yourself_how', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('prediction_playground.basedataentry',),
        ),
    ]
